<?php if ( !defined('BASEPATH')) header('Location:/404');
/**
 * RSS for PHP - small and easy-to-use library for consuming an RSS Feed
 * Adding default URL/Server for data request from http://news.google.com
 *
 * @author David Grudl
 * @author Change httpRequest to _RetrieveXML using cURLs class (dir="vendor/curl.php")
 * @copyright Copyright (c) 2008 - 2014 David Grudl & Ofan Ebob
 * @license New BSD License
 * @version 1.1
 */
class NewsGoogleFeed
{
	/** @var int */
	public static $cacheExpire = 86400; // 1 day

	/** @var SimpleXMLElement */
	protected $xml;


	/**
	 * Returns property value. Do not call directly.
	 * @param  string  tag name
	 * @return SimpleXMLElement
	 */
	public function __get($name)
	{
		return $this->xml->{$name};
	}


	/**
	 * Sets value of a property. Do not call directly.
	 * @param  string  property name
	 * @param  mixed   property value
	 * @return void
	 */
	public function __set($name, $value)
	{
		throw new NewsGoogleFeedException("Cannot assign to a read-only property '$name'.");
	}
	

	/**
	 * Loads RSS channel.
	 * @param  string  RSS feed URL
	 * @param  string  optional user name
	 * @param  string  optional password
	 * @return Feed
	 * @throws NewsGoogleFeedException
	 */
	public static function loadRss($query)
	{
		$xml = new SimpleXMLElement(self::_RetrieveXML($query), LIBXML_NOWARNING | LIBXML_NOERROR);
		
		if(!$xml->channel)
		{
			throw new NewsGoogleFeedException('Invalid channel.');
		}

		self::adjustNamespaces($xml->channel);

		foreach ($xml->channel->item as $item)
		{
			// converts namespaces to dotted tags
			self::adjustNamespaces($item);

			// generate 'timestamp' tag
			if(isset($item->{'dc:date'}))
			{
				$item->timestamp = strtotime($item->{'dc:date'});
			}
			elseif(isset($item->pubDate))
			{
				$item->timestamp = strtotime($item->pubDate);
			}
		}

		$feed = new self;
		$feed->xml = $xml->channel;
		return $feed;
	}


	/**
	 * Loads Atom channel.
	 * @param  string  Atom feed URL
	 * @param  string  optional user name
	 * @param  string  optional password
	 * @return Feed
	 * @throws NewsGoogleFeedException
	 */
	public static function loadAtom($query)
	{
		$xml = new SimpleXMLElement(self::_RetrieveXML($query), LIBXML_NOWARNING | LIBXML_NOERROR);
		if(!in_array('http://www.w3.org/2005/Atom', $xml->getDocNamespaces(), TRUE))
		{
			throw new NewsGoogleFeedException('Invalid channel.');
		}

		// generate 'timestamp' tag
		foreach ($xml->entry as $entry)
		{
			$entry->timestamp = strtotime($entry->updated);
		}

		$feed = new self;
		$feed->xml = $xml;
		return $feed;
	}


	/**
	 * Retrive XML.
	 * @param  string query
	 * @return string
	 * @throws NewsGoogleFeedException
	 */
	private static function _RetrieveXML($query)
	{
		try
		{
			$basePath = (defined('BASEPATH') ? BASEPATH : dirname(__FILE__).'/../../');
			
			$cache_dir = $basePath.'/app/news/xml';

			$expire_cache = strtotime('+1 Day');

			// Cache Handler
			$data = CacheHandler::save(array('method'=>array('NewsGoogleFeed','_RequestData'),
											 'data'=>$query,
											 'cache_expire'=>$expire_cache,
											 'cache_prefix'=>'feed',
											 'cache_id'=>$query,
											 'cache_dir'=>$cache_dir,
											 'format'=>'xml',
											 //'type_save'=>'database',
											 //'serialize'=>false
											 )
										);

			return $data;
		}
		catch(CacheHandlerException $e)
		{
			throw new NewsGoogleFeedException($e->getMessage());
		}
	}


	/**
	 * Request Data with cURLs method
	 * @param  string query
	 * @return string
	 * @throws NewsGoogleFeedException
	 */
	public static function _RequestData($query)
	{
		if(method_exists('cURLs','access_curl'))
		{
			$server = 'http://news.google.com/news/section';
			$query = urlencode($query);
			$BuildURI = $server.'?q='.$query.'&output=rss';

			$data = array('url'=>$BuildURI,'type'=>'data');
			$cURLs = new cURLs($data);
			return $cURLs->access_curl();
		}
		else
		{
			return null;
		}
	}


	/**
	 * Generates better accessible namespaced tags.
	 * @param  SimpleXMLElement
	 * @return void
	 */
	private static function adjustNamespaces($el)
	{
		foreach ($el->getNamespaces(TRUE) as $prefix => $ns)
		{
			$children = $el->children($ns);
			foreach ($children as $tag => $content)
			{
				$el->{$prefix . ':' . $tag} = $content;
			}
		}
	}


	/**
	 * Converts a SimpleXMLElement into an array.
	 * @return array
	 */
	private static function NewsXMLtoArray($xml = NULL)
	{
		$xml = new SimpleXMLElement($xml);
	    if($xml === NULL)
	    {
	        $xml = $this->xml;
	    }

	    if(!$xml->children())
	    {
	        return (string) $xml;
	    }

	    $arr = array();
	    foreach ($xml->children() as $tag => $child)
	    {
	        if(count($xml->$tag) === 1)
	        {
	            $arr[$tag] = self::NewsXMLtoArray($child);
	        }
	        else
	        {
	            $arr[$tag][] = self::NewsXMLtoArray($child);
	        }
	    }

	    return $arr;
	}
}


/**
 * An exception generated by Feed.
 */
class NewsGoogleFeedException extends Exception{}
?>
